### ISSUE TITLE
cancelled events in AN showing up on map

### ISSUE THREAD

**Issue by suzigrishpul** [350org/megamap#10]
this event has been cancelled in AN: https://cl.ly/0p11273J3X2Y
but is still showing on the map: https://cl.ly/2J2Q012L2o07

**Comment by rapicastillo** [comment]
Map shows active events, removing cancelled ones.

**Comment by rapicastillo** [comment]
This has been fixed at 2ce889dab1bc02b39932ad7c8078fcdb9d6f2349
